name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  deploy-to-wsl:
    runs-on: self-hosted
    needs: build-and-push

    steps:
    - name: Pull and run container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
        docker stop myapp || true && docker rm myapp || true
        docker run -d --name myapp -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
